services:
  watchtower:
    image: containrrr/watchtower
    labels:
      - "--lable-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=bhargavasharabha@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./var/run/docker.sock:/var/run/docker.sock
  www:
    image: usabsp/oscg-www:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`oursaviourcommunitygarden.org`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    # ports:
    #   - "3002:80"
    restart: always

  login:
    image: usabsp/oscg-login:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.login.rule=Host(`admin.oursaviourcommunitygarden.org`)"
      - "traefik.http.routers.login.entrypoints=websecure"
      - "traefik.http.routers.login.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    # ports:
    #   - "3005:80"
    restart: always

  fastapi:
    image: usabsp/oscg-fastapi:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # ports:
    #   - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ItemRaj@1562
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  letsencrypt: